---
title: "capstone_data_analysis"
author: "Evan O'Keefe"
date: "3/7/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

vickers <- read_csv("vickers-data-analysis.csv")
standards = data.frame(material = c("Bronze", "Copper"), hardness = c(107, 50))

vickers <- vickers %>%
  mutate(name = paste("Sample", id)) %>% 
  pivot_longer(
    cols = starts_with("measure"),
    names_to = "test",
    names_prefix = "measure_",
    values_to = "hardness"
  )
```

```{r}
ggplot(vickers, aes(x = material, y = hardness)) +
  geom_boxplot() +
  geom_point(aes(color = "Experimental")) +
  geom_point(data = standards, aes(color = "Standard"), size = 2) +
  theme_minimal() +
  labs(
    title = "Vicker's Microhardness of Copper & Bronze Samples",
    x = "",
    y = "Hardness (HV)"
  ) +
  scale_color_manual(name = "",
                     breaks = c("Experimental", "Standard"),
                     values = c("Experimental"="black", "Standard"="red"))
```

```{r}
ggplot(vickers, aes(x = reorder(name, id), y = hardness)) +
  geom_hline(data = standards,
             aes(yintercept = hardness,
                 color = "Standard"),
             linetype = "dashed",
             size = 2) +
  geom_point(size = 2.5) +
  theme_bw() +
  facet_wrap(
    ~material,
    nrow = 2,
    scales = "free") +
  labs(
    title = "Distribution of Hardness Values Over Each Sample",
    x = "",
    y = "Hardness (HV)"
  ) +
  scale_color_manual(name = "",
                     breaks = c("Standard"),
                     values = c("Standard"="red")) +
  theme(
    text = element_text(size = 16),
    plot.title = element_text(size = 24),
    axis.title = element_text(size = 18)
  )

ggsave("point-plot-hardness.png", width = 12, height = 6, units = "in")
```

```{r}
bronze_hw <- read_csv("bronze-height-width.csv")

bronze_df <- vickers %>%
  filter(material == "Bronze") %>% 
  group_by(id) %>% 
  summarise(hardness = mean(hardness), name = unique(name)) %>% 
  merge(bronze_hw) %>% 
  mutate(shrink = (Face - Center) / Face)
```

```{r}
library(ggrepel)

ggplot(bronze_df, aes(x = shrink*100, y = hardness)) +
  geom_point() +
  geom_text_repel(aes(label = name), nudge_x = -0.5) +
  theme_light() +
  labs(
    title = "Center Shrinkage vs Hardness",
    x = "Center Shrinkage (%)",
    y = "Hardness (HV)"
  ) +
  theme(
    text = element_text(size = 16),
    plot.title = element_text(size = 24),
    axis.title = element_text(size = 18)
  )

ggsave("scatterplot-shrink-hard.png", width = 6, height = 6, units = "in")
```

```{r}
bronze_df2 <- vickers %>%
  filter(material == "Bronze") %>% 
  merge(bronze_hw) %>% 
  mutate(shrink = (Face - Center) / Face)
```

